export const bracket = [
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1BDj5lr0KVcSQpSNdyqJct',
      },
      href: 'https://api.spotify.com/v1/albums/1BDj5lr0KVcSQpSNdyqJct',
      id: '1BDj5lr0KVcSQpSNdyqJct',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27394bd724b5ac47de78be093fd',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0294bd724b5ac47de78be093fd',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485194bd724b5ac47de78be093fd',
          width: 64,
        },
      ],
      name: 'This Is Why',
      release_date: '2022-09-28',
      release_date_precision: 'day',
      total_tracks: 1,
      type: 'album',
      uri: 'spotify:album:1BDj5lr0KVcSQpSNdyqJct',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 207652,
    explicit: false,
    external_ids: {
      isrc: 'USAT22215020',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/7z84Fwf1R3Z2BwHCP620CI',
    },
    href: 'https://api.spotify.com/v1/tracks/7z84Fwf1R3Z2BwHCP620CI',
    id: '7z84Fwf1R3Z2BwHCP620CI',
    is_local: false,
    name: 'This Is Why',
    popularity: 0,
    preview_url:
      'https://p.scdn.co/mp3-preview/64b3363745bcb96bcd2f3c3a9497c1d078699d45?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:7z84Fwf1R3Z2BwHCP620CI',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BN',
        'BO',
        'BR',
        'BS',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GR',
        'GT',
        'GW',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LK',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MD',
        'ME',
        'MK',
        'MN',
        'MO',
        'MT',
        'MU',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'SZ',
        'TD',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TR',
        'TT',
        'TW',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'XK',
        'ZA',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/4sgYpkIASM1jVlNC8Wp9oF',
      },
      href: 'https://api.spotify.com/v1/albums/4sgYpkIASM1jVlNC8Wp9oF',
      id: '4sgYpkIASM1jVlNC8Wp9oF',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e71a5005c37e8c2ffd9beda8',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e71a5005c37e8c2ffd9beda8',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e71a5005c37e8c2ffd9beda8',
          width: 64,
        },
      ],
      name: 'Paramore',
      release_date: '2013-04-05',
      release_date_precision: 'day',
      total_tracks: 17,
      type: 'album',
      uri: 'spotify:album:4sgYpkIASM1jVlNC8Wp9oF',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AG',
      'AL',
      'AM',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BN',
      'BO',
      'BR',
      'BS',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GR',
      'GT',
      'GW',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LK',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MD',
      'ME',
      'MK',
      'MN',
      'MO',
      'MT',
      'MU',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'SZ',
      'TD',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TR',
      'TT',
      'TW',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'XK',
      'ZA',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 216013,
    explicit: false,
    external_ids: {
      isrc: 'USAT21300012',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1yjY7rpaAQvKwpdUliHx0d',
    },
    href: 'https://api.spotify.com/v1/tracks/1yjY7rpaAQvKwpdUliHx0d',
    id: '1yjY7rpaAQvKwpdUliHx0d',
    is_local: false,
    name: 'Still into You',
    popularity: 79,
    preview_url:
      'https://p.scdn.co/mp3-preview/c029f0bab41d914de58b193af43a9c82504dc005?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 9,
    type: 'track',
    uri: 'spotify:track:1yjY7rpaAQvKwpdUliHx0d',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: ['BR', 'CA', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/71rziY9eLo1tA2dBMxrwhc',
      },
      href: 'https://api.spotify.com/v1/albums/71rziY9eLo1tA2dBMxrwhc',
      id: '71rziY9eLo1tA2dBMxrwhc',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273bee754528c08d5ff6799a1eb',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02bee754528c08d5ff6799a1eb',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851bee754528c08d5ff6799a1eb',
          width: 64,
        },
      ],
      name: 'Riot!',
      release_date: '2007-06-11',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:71rziY9eLo1tA2dBMxrwhc',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: ['BR', 'CA', 'US'],
    disc_number: 1,
    duration_ms: 211520,
    explicit: false,
    external_ids: {
      isrc: 'USAT20702617',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6SpLc7EXZIPpy0sVko0aoU',
    },
    href: 'https://api.spotify.com/v1/tracks/6SpLc7EXZIPpy0sVko0aoU',
    id: '6SpLc7EXZIPpy0sVko0aoU',
    is_local: false,
    name: 'Misery Business',
    popularity: 76,
    preview_url:
      'https://p.scdn.co/mp3-preview/c95e281bf76899c1d7a0cf22afeb832e32fc061f?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 4,
    type: 'track',
    uri: 'spotify:track:6SpLc7EXZIPpy0sVko0aoU',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1c9Sx7XdXuMptGyfCB6hHs',
      },
      href: 'https://api.spotify.com/v1/albums/1c9Sx7XdXuMptGyfCB6hHs',
      id: '1c9Sx7XdXuMptGyfCB6hHs',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273dbd83e179619408e5d05cc99',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02dbd83e179619408e5d05cc99',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851dbd83e179619408e5d05cc99',
          width: 64,
        },
      ],
      name: 'After Laughter',
      release_date: '2017-05-12',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:1c9Sx7XdXuMptGyfCB6hHs',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 182693,
    explicit: false,
    external_ids: {
      isrc: 'USAT21700948',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/0w5Bdu51Ka25Pf3hojsKHh',
    },
    href: 'https://api.spotify.com/v1/tracks/0w5Bdu51Ka25Pf3hojsKHh',
    id: '0w5Bdu51Ka25Pf3hojsKHh',
    is_local: false,
    name: 'Hard Times',
    popularity: 74,
    preview_url:
      'https://p.scdn.co/mp3-preview/9ce352263b812b62cffb9d54401c53ec56750e2b?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:0w5Bdu51Ka25Pf3hojsKHh',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AR',
        'BD',
        'BE',
        'BH',
        'BN',
        'BO',
        'BR',
        'BZ',
        'CA',
        'CL',
        'CO',
        'CR',
        'CW',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EG',
        'ES',
        'FI',
        'FR',
        'GR',
        'GT',
        'GY',
        'HK',
        'HN',
        'ID',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JO',
        'KH',
        'KR',
        'KW',
        'LA',
        'LB',
        'LK',
        'LU',
        'LY',
        'MA',
        'MO',
        'MT',
        'MX',
        'MY',
        'NG',
        'NI',
        'NL',
        'NO',
        'OM',
        'PA',
        'PE',
        'PH',
        'PK',
        'PS',
        'PT',
        'PY',
        'QA',
        'SA',
        'SE',
        'SG',
        'SR',
        'SV',
        'TH',
        'TL',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VE',
        'VN',
        'ZA',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/27UqZoE1kV6sIV6uQcI28A',
      },
      href: 'https://api.spotify.com/v1/albums/27UqZoE1kV6sIV6uQcI28A',
      id: '27UqZoE1kV6sIV6uQcI28A',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e01d7d558032457b0e4883f6',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e01d7d558032457b0e4883f6',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e01d7d558032457b0e4883f6',
          width: 64,
        },
      ],
      name: 'Brand New Eyes',
      release_date: '2009-09-28',
      release_date_precision: 'day',
      total_tracks: 11,
      type: 'album',
      uri: 'spotify:album:27UqZoE1kV6sIV6uQcI28A',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AR',
      'BD',
      'BE',
      'BH',
      'BN',
      'BO',
      'BR',
      'BZ',
      'CA',
      'CL',
      'CO',
      'CR',
      'CW',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EG',
      'ES',
      'FI',
      'FR',
      'GR',
      'GT',
      'GY',
      'HK',
      'HN',
      'ID',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JO',
      'KH',
      'KR',
      'KW',
      'LA',
      'LB',
      'LK',
      'LU',
      'LY',
      'MA',
      'MO',
      'MT',
      'MX',
      'MY',
      'NG',
      'NI',
      'NL',
      'NO',
      'OM',
      'PA',
      'PE',
      'PH',
      'PK',
      'PS',
      'PT',
      'PY',
      'QA',
      'SA',
      'SE',
      'SG',
      'SR',
      'SV',
      'TH',
      'TL',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VE',
      'VN',
      'ZA',
    ],
    disc_number: 1,
    duration_ms: 267653,
    explicit: false,
    external_ids: {
      isrc: 'USAT20902323',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/7JIuqL4ZqkpfGKQhYlrirs',
    },
    href: 'https://api.spotify.com/v1/tracks/7JIuqL4ZqkpfGKQhYlrirs',
    id: '7JIuqL4ZqkpfGKQhYlrirs',
    is_local: false,
    name: 'The Only Exception',
    popularity: 73,
    preview_url:
      'https://p.scdn.co/mp3-preview/6979ca4b9bdfa60d942d45cf7b7e6b967e7cc6f1?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 6,
    type: 'track',
    uri: 'spotify:track:7JIuqL4ZqkpfGKQhYlrirs',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BN',
        'BO',
        'BR',
        'BS',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GR',
        'GT',
        'GW',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LK',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MD',
        'ME',
        'MK',
        'MN',
        'MO',
        'MT',
        'MU',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'SZ',
        'TD',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TR',
        'TT',
        'TW',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'XK',
        'ZA',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/4sgYpkIASM1jVlNC8Wp9oF',
      },
      href: 'https://api.spotify.com/v1/albums/4sgYpkIASM1jVlNC8Wp9oF',
      id: '4sgYpkIASM1jVlNC8Wp9oF',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e71a5005c37e8c2ffd9beda8',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e71a5005c37e8c2ffd9beda8',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e71a5005c37e8c2ffd9beda8',
          width: 64,
        },
      ],
      name: 'Paramore',
      release_date: '2013-04-05',
      release_date_precision: 'day',
      total_tracks: 17,
      type: 'album',
      uri: 'spotify:album:4sgYpkIASM1jVlNC8Wp9oF',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AG',
      'AL',
      'AM',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BN',
      'BO',
      'BR',
      'BS',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GR',
      'GT',
      'GW',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LK',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MD',
      'ME',
      'MK',
      'MN',
      'MO',
      'MT',
      'MU',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'SZ',
      'TD',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TR',
      'TT',
      'TW',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'XK',
      'ZA',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 296520,
    explicit: false,
    external_ids: {
      isrc: 'USAT21300009',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1j8z4TTjJ1YOdoFEDwJTQa',
    },
    href: 'https://api.spotify.com/v1/tracks/1j8z4TTjJ1YOdoFEDwJTQa',
    id: '1j8z4TTjJ1YOdoFEDwJTQa',
    is_local: false,
    name: "Ain't It Fun",
    popularity: 74,
    preview_url:
      'https://p.scdn.co/mp3-preview/ded65c8e0e9707b4c6b2cfc0bfd7c0bc6bb87960?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 6,
    type: 'track',
    uri: 'spotify:track:1j8z4TTjJ1YOdoFEDwJTQa',
  },
  {
    album: {
      album_type: 'single',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/70iJhodSPkl7FR1VW4n0KF',
      },
      href: 'https://api.spotify.com/v1/albums/70iJhodSPkl7FR1VW4n0KF',
      id: '70iJhodSPkl7FR1VW4n0KF',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273b236d0eae2659e7e7adb8b56',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02b236d0eae2659e7e7adb8b56',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851b236d0eae2659e7e7adb8b56',
          width: 64,
        },
      ],
      name: 'Decode',
      release_date: '2008-11-04',
      release_date_precision: 'day',
      total_tracks: 1,
      type: 'album',
      uri: 'spotify:album:70iJhodSPkl7FR1VW4n0KF',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 261959,
    explicit: false,
    external_ids: {
      isrc: 'USAT22103220',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1ZLtE9tSJdaUiIJ9YoKHQe',
    },
    href: 'https://api.spotify.com/v1/tracks/1ZLtE9tSJdaUiIJ9YoKHQe',
    id: '1ZLtE9tSJdaUiIJ9YoKHQe',
    is_local: false,
    name: 'Decode',
    popularity: 71,
    preview_url:
      'https://p.scdn.co/mp3-preview/21e68e1b032086dcf83e2f573f303b8d40a23724?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:1ZLtE9tSJdaUiIJ9YoKHQe',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: ['BR', 'CA', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/71rziY9eLo1tA2dBMxrwhc',
      },
      href: 'https://api.spotify.com/v1/albums/71rziY9eLo1tA2dBMxrwhc',
      id: '71rziY9eLo1tA2dBMxrwhc',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273bee754528c08d5ff6799a1eb',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02bee754528c08d5ff6799a1eb',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851bee754528c08d5ff6799a1eb',
          width: 64,
        },
      ],
      name: 'Riot!',
      release_date: '2007-06-11',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:71rziY9eLo1tA2dBMxrwhc',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: ['BR', 'CA', 'US'],
    disc_number: 1,
    duration_ms: 220480,
    explicit: false,
    external_ids: {
      isrc: 'USAT20702601',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1JdKrFyoU05abww0Zv0ayQ',
    },
    href: 'https://api.spotify.com/v1/tracks/1JdKrFyoU05abww0Zv0ayQ',
    id: '1JdKrFyoU05abww0Zv0ayQ',
    is_local: false,
    name: "That's What You Get",
    popularity: 68,
    preview_url:
      'https://p.scdn.co/mp3-preview/f54b9a823af9d987f88d85d35d312464a8388dcc?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:1JdKrFyoU05abww0Zv0ayQ',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AR',
        'BD',
        'BE',
        'BH',
        'BN',
        'BO',
        'BR',
        'BZ',
        'CA',
        'CL',
        'CO',
        'CR',
        'CW',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EG',
        'ES',
        'FI',
        'FR',
        'GR',
        'GT',
        'GY',
        'HK',
        'HN',
        'ID',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JO',
        'KH',
        'KR',
        'KW',
        'LA',
        'LB',
        'LK',
        'LU',
        'LY',
        'MA',
        'MO',
        'MT',
        'MX',
        'MY',
        'NG',
        'NI',
        'NL',
        'NO',
        'OM',
        'PA',
        'PE',
        'PH',
        'PK',
        'PS',
        'PT',
        'PY',
        'QA',
        'SA',
        'SE',
        'SG',
        'SR',
        'SV',
        'TH',
        'TL',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VE',
        'VN',
        'ZA',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/27UqZoE1kV6sIV6uQcI28A',
      },
      href: 'https://api.spotify.com/v1/albums/27UqZoE1kV6sIV6uQcI28A',
      id: '27UqZoE1kV6sIV6uQcI28A',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e01d7d558032457b0e4883f6',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e01d7d558032457b0e4883f6',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e01d7d558032457b0e4883f6',
          width: 64,
        },
      ],
      name: 'Brand New Eyes',
      release_date: '2009-09-28',
      release_date_precision: 'day',
      total_tracks: 11,
      type: 'album',
      uri: 'spotify:album:27UqZoE1kV6sIV6uQcI28A',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AR',
      'BD',
      'BE',
      'BH',
      'BN',
      'BO',
      'BR',
      'BZ',
      'CA',
      'CL',
      'CO',
      'CR',
      'CW',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EG',
      'ES',
      'FI',
      'FR',
      'GR',
      'GT',
      'GY',
      'HK',
      'HN',
      'ID',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JO',
      'KH',
      'KR',
      'KW',
      'LA',
      'LB',
      'LK',
      'LU',
      'LY',
      'MA',
      'MO',
      'MT',
      'MX',
      'MY',
      'NG',
      'NI',
      'NL',
      'NO',
      'OM',
      'PA',
      'PE',
      'PH',
      'PK',
      'PS',
      'PT',
      'PY',
      'QA',
      'SA',
      'SE',
      'SG',
      'SR',
      'SV',
      'TH',
      'TL',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VE',
      'VN',
      'ZA',
    ],
    disc_number: 1,
    duration_ms: 225786,
    explicit: false,
    external_ids: {
      isrc: 'USAT20902328',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1Bv3h7Vc4AaYA2BcSM3rVd',
    },
    href: 'https://api.spotify.com/v1/tracks/1Bv3h7Vc4AaYA2BcSM3rVd',
    id: '1Bv3h7Vc4AaYA2BcSM3rVd',
    is_local: false,
    name: 'All I Wanted',
    popularity: 71,
    preview_url:
      'https://p.scdn.co/mp3-preview/7801295a5fbf9c24650f0b4217072f4f198dad51?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 11,
    type: 'track',
    uri: 'spotify:track:1Bv3h7Vc4AaYA2BcSM3rVd',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BN',
        'BO',
        'BR',
        'BS',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GR',
        'GT',
        'GW',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LK',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MD',
        'ME',
        'MK',
        'MN',
        'MO',
        'MT',
        'MU',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'SZ',
        'TD',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TR',
        'TT',
        'TW',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'XK',
        'ZA',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/4sgYpkIASM1jVlNC8Wp9oF',
      },
      href: 'https://api.spotify.com/v1/albums/4sgYpkIASM1jVlNC8Wp9oF',
      id: '4sgYpkIASM1jVlNC8Wp9oF',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e71a5005c37e8c2ffd9beda8',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e71a5005c37e8c2ffd9beda8',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e71a5005c37e8c2ffd9beda8',
          width: 64,
        },
      ],
      name: 'Paramore',
      release_date: '2013-04-05',
      release_date_precision: 'day',
      total_tracks: 17,
      type: 'album',
      uri: 'spotify:album:4sgYpkIASM1jVlNC8Wp9oF',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AG',
      'AL',
      'AM',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BN',
      'BO',
      'BR',
      'BS',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GR',
      'GT',
      'GW',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LK',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MD',
      'ME',
      'MK',
      'MN',
      'MO',
      'MT',
      'MU',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'SZ',
      'TD',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TR',
      'TT',
      'TW',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'XK',
      'ZA',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 52600,
    explicit: false,
    external_ids: {
      isrc: 'USAT21300018',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/2GBjsCkCpR5w8Zri9aE49H',
    },
    href: 'https://api.spotify.com/v1/tracks/2GBjsCkCpR5w8Zri9aE49H',
    id: '2GBjsCkCpR5w8Zri9aE49H',
    is_local: false,
    name: "Interlude: I'm Not Angry Anymore",
    popularity: 68,
    preview_url:
      'https://p.scdn.co/mp3-preview/a5e9d5024180ea8dd609d57411fec8fb7ea130fc?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 15,
    type: 'track',
    uri: 'spotify:track:2GBjsCkCpR5w8Zri9aE49H',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1c9Sx7XdXuMptGyfCB6hHs',
      },
      href: 'https://api.spotify.com/v1/albums/1c9Sx7XdXuMptGyfCB6hHs',
      id: '1c9Sx7XdXuMptGyfCB6hHs',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273dbd83e179619408e5d05cc99',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02dbd83e179619408e5d05cc99',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851dbd83e179619408e5d05cc99',
          width: 64,
        },
      ],
      name: 'After Laughter',
      release_date: '2017-05-12',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:1c9Sx7XdXuMptGyfCB6hHs',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 212853,
    explicit: false,
    external_ids: {
      isrc: 'USAT21700950',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/2RJfK2pOvGpnxC255YOy5k',
    },
    href: 'https://api.spotify.com/v1/tracks/2RJfK2pOvGpnxC255YOy5k',
    id: '2RJfK2pOvGpnxC255YOy5k',
    is_local: false,
    name: 'Rose-Colored Boy',
    popularity: 64,
    preview_url:
      'https://p.scdn.co/mp3-preview/ed2ffc566cf0558a01f7df544cc048403dc38804?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:2RJfK2pOvGpnxC255YOy5k',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: ['BR', 'CA', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/71rziY9eLo1tA2dBMxrwhc',
      },
      href: 'https://api.spotify.com/v1/albums/71rziY9eLo1tA2dBMxrwhc',
      id: '71rziY9eLo1tA2dBMxrwhc',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273bee754528c08d5ff6799a1eb',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02bee754528c08d5ff6799a1eb',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851bee754528c08d5ff6799a1eb',
          width: 64,
        },
      ],
      name: 'Riot!',
      release_date: '2007-06-11',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:71rziY9eLo1tA2dBMxrwhc',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: ['BR', 'CA', 'US'],
    disc_number: 1,
    duration_ms: 189373,
    explicit: false,
    external_ids: {
      isrc: 'USAT20702606',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/3VA4sjTMSTTF02hFGmlpJh',
    },
    href: 'https://api.spotify.com/v1/tracks/3VA4sjTMSTTF02hFGmlpJh',
    id: '3VA4sjTMSTTF02hFGmlpJh',
    is_local: false,
    name: 'crushcrushcrush',
    popularity: 66,
    preview_url:
      'https://p.scdn.co/mp3-preview/f14bac4511aa3f5a6f7e5cfc7f9f567833149ab7?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 8,
    type: 'track',
    uri: 'spotify:track:3VA4sjTMSTTF02hFGmlpJh',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AR',
        'BD',
        'BE',
        'BH',
        'BN',
        'BO',
        'BR',
        'BZ',
        'CA',
        'CL',
        'CO',
        'CR',
        'CW',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EG',
        'ES',
        'FI',
        'FR',
        'GR',
        'GT',
        'GY',
        'HK',
        'HN',
        'ID',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JO',
        'KH',
        'KR',
        'KW',
        'LA',
        'LB',
        'LK',
        'LU',
        'LY',
        'MA',
        'MO',
        'MT',
        'MX',
        'MY',
        'NG',
        'NI',
        'NL',
        'NO',
        'OM',
        'PA',
        'PE',
        'PH',
        'PK',
        'PS',
        'PT',
        'PY',
        'QA',
        'SA',
        'SE',
        'SG',
        'SR',
        'SV',
        'TH',
        'TL',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VE',
        'VN',
        'ZA',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/27UqZoE1kV6sIV6uQcI28A',
      },
      href: 'https://api.spotify.com/v1/albums/27UqZoE1kV6sIV6uQcI28A',
      id: '27UqZoE1kV6sIV6uQcI28A',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e01d7d558032457b0e4883f6',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e01d7d558032457b0e4883f6',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e01d7d558032457b0e4883f6',
          width: 64,
        },
      ],
      name: 'Brand New Eyes',
      release_date: '2009-09-28',
      release_date_precision: 'day',
      total_tracks: 11,
      type: 'album',
      uri: 'spotify:album:27UqZoE1kV6sIV6uQcI28A',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AR',
      'BD',
      'BE',
      'BH',
      'BN',
      'BO',
      'BR',
      'BZ',
      'CA',
      'CL',
      'CO',
      'CR',
      'CW',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EG',
      'ES',
      'FI',
      'FR',
      'GR',
      'GT',
      'GY',
      'HK',
      'HN',
      'ID',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JO',
      'KH',
      'KR',
      'KW',
      'LA',
      'LB',
      'LK',
      'LU',
      'LY',
      'MA',
      'MO',
      'MT',
      'MX',
      'MY',
      'NG',
      'NI',
      'NL',
      'NO',
      'OM',
      'PA',
      'PE',
      'PH',
      'PK',
      'PS',
      'PT',
      'PY',
      'QA',
      'SA',
      'SE',
      'SG',
      'SR',
      'SV',
      'TH',
      'TL',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VE',
      'VN',
      'ZA',
    ],
    disc_number: 1,
    duration_ms: 218626,
    explicit: false,
    external_ids: {
      isrc: 'USAT20902050',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/47No93LxERvV6MtOAmQzHS',
    },
    href: 'https://api.spotify.com/v1/tracks/47No93LxERvV6MtOAmQzHS',
    id: '47No93LxERvV6MtOAmQzHS',
    is_local: false,
    name: 'Ignorance',
    popularity: 68,
    preview_url:
      'https://p.scdn.co/mp3-preview/35aa876da41d56dee3edb8b0973480bf8c94fee8?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:47No93LxERvV6MtOAmQzHS',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/67f6SSb8yKduNCK15DsafC',
      },
      href: 'https://api.spotify.com/v1/albums/67f6SSb8yKduNCK15DsafC',
      id: '67f6SSb8yKduNCK15DsafC',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b2735cab62839794c2cc3d6a135b',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e025cab62839794c2cc3d6a135b',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d000048515cab62839794c2cc3d6a135b',
          width: 64,
        },
      ],
      name: 'All We Know Is Falling',
      release_date: '2005-07-26',
      release_date_precision: 'day',
      total_tracks: 10,
      type: 'album',
      uri: 'spotify:album:67f6SSb8yKduNCK15DsafC',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 185733,
    explicit: false,
    external_ids: {
      isrc: 'US56V0507602',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/7mG2RbhyzGsjpQOz568d39',
    },
    href: 'https://api.spotify.com/v1/tracks/7mG2RbhyzGsjpQOz568d39',
    id: '7mG2RbhyzGsjpQOz568d39',
    is_local: false,
    name: 'Pressure',
    popularity: 63,
    preview_url:
      'https://p.scdn.co/mp3-preview/0fc0be409dec2d9883b75d4b2a93f85ab28426f4?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:7mG2RbhyzGsjpQOz568d39',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/1c9Sx7XdXuMptGyfCB6hHs',
      },
      href: 'https://api.spotify.com/v1/albums/1c9Sx7XdXuMptGyfCB6hHs',
      id: '1c9Sx7XdXuMptGyfCB6hHs',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273dbd83e179619408e5d05cc99',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02dbd83e179619408e5d05cc99',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851dbd83e179619408e5d05cc99',
          width: 64,
        },
      ],
      name: 'After Laughter',
      release_date: '2017-05-12',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:1c9Sx7XdXuMptGyfCB6hHs',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 235706,
    explicit: false,
    external_ids: {
      isrc: 'USAT21700953',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6t44iU80A0h8WQ7vc4OoRj',
    },
    href: 'https://api.spotify.com/v1/tracks/6t44iU80A0h8WQ7vc4OoRj',
    id: '6t44iU80A0h8WQ7vc4OoRj',
    is_local: false,
    name: 'Fake Happy',
    popularity: 63,
    preview_url:
      'https://p.scdn.co/mp3-preview/354a68315386fcea11e99800e9e1871c9c6ab6ae?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 5,
    type: 'track',
    uri: 'spotify:track:6t44iU80A0h8WQ7vc4OoRj',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
          },
          href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
          id: '74XFHRwlV6OrjEM0A2NCMF',
          name: 'Paramore',
          type: 'artist',
          uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
        },
      ],
      available_markets: [
        'AE',
        'AG',
        'AL',
        'AM',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BN',
        'BO',
        'BR',
        'BS',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GR',
        'GT',
        'GW',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LK',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MD',
        'ME',
        'MK',
        'MN',
        'MO',
        'MT',
        'MU',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PT',
        'PY',
        'QA',
        'RO',
        'RS',
        'SA',
        'SE',
        'SG',
        'SI',
        'SK',
        'SV',
        'SZ',
        'TD',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TR',
        'TT',
        'TW',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'XK',
        'ZA',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/4sgYpkIASM1jVlNC8Wp9oF',
      },
      href: 'https://api.spotify.com/v1/albums/4sgYpkIASM1jVlNC8Wp9oF',
      id: '4sgYpkIASM1jVlNC8Wp9oF',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273e71a5005c37e8c2ffd9beda8',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02e71a5005c37e8c2ffd9beda8',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851e71a5005c37e8c2ffd9beda8',
          width: 64,
        },
      ],
      name: 'Paramore',
      release_date: '2013-04-05',
      release_date_precision: 'day',
      total_tracks: 17,
      type: 'album',
      uri: 'spotify:album:4sgYpkIASM1jVlNC8Wp9oF',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF',
        },
        href: 'https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF',
        id: '74XFHRwlV6OrjEM0A2NCMF',
        name: 'Paramore',
        type: 'artist',
        uri: 'spotify:artist:74XFHRwlV6OrjEM0A2NCMF',
      },
    ],
    available_markets: [
      'AE',
      'AG',
      'AL',
      'AM',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BN',
      'BO',
      'BR',
      'BS',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GR',
      'GT',
      'GW',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LK',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MD',
      'ME',
      'MK',
      'MN',
      'MO',
      'MT',
      'MU',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'RS',
      'SA',
      'SE',
      'SG',
      'SI',
      'SK',
      'SV',
      'SZ',
      'TD',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TR',
      'TT',
      'TW',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'XK',
      'ZA',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 309973,
    explicit: false,
    external_ids: {
      isrc: 'USAT21300011',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/2VBluJiNj9bKohWX0dY1Lh',
    },
    href: 'https://api.spotify.com/v1/tracks/2VBluJiNj9bKohWX0dY1Lh',
    id: '2VBluJiNj9bKohWX0dY1Lh',
    is_local: false,
    name: 'Last Hope',
    popularity: 61,
    preview_url:
      'https://p.scdn.co/mp3-preview/e2fe36f5529fd1b63511588258e87eaa7025c74f?cid=adaaf209fb064dfab873a71817029e0d',
    track_number: 8,
    type: 'track',
    uri: 'spotify:track:2VBluJiNj9bKohWX0dY1Lh',
  },
]

export const relevantInfo = bracket.map((a) => {
  return {
    albumArt: a.album.images[0].url,
    albumArtTiny: a.album.images[a.album.images.length - 1].url,
    name: a.name,
    artist: a.artists.map((artist) => artist.name).join(', '),
    preview: a.preview_url,
  }
})

export type IBracketEntry = typeof relevantInfo[number]
